backend:
  name: git-gateway
  branch: master

media_folder: static/public
public_folder: /public
publish_mode: editorial_workflow

collections:
  - name: "article"
    label: "Article"
    folder: "src/pages/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
